### ISSUE TITLE
image not identifies 

### ISSUE THREAD

**Issue by BeingTraveler** [GaganHonor/Face-Identification-System-#2]
# Bug report: Images not recognized in OpenCV project

## Description

I encountered a bug when trying to run the OpenCV project on my machine. The project does not recognize the images in the input folder and throws an error.

## Steps to reproduce

1. Clone the repository from https://github.com/GaganHonor/Face-Identification-System-
2. Install the dependencies with `pip install -r requirements.txt`
3. Run the main script with `python main.py --input input/ --output output/`
4. Observe the error message: `cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-99ib2vsi/opencv/modules/imgproc/src/resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

## Expected behavior

The project should process the images in the input folder and save the results in the output folder.

## Actual behavior

The project fails to recognize the images in the input folder and throws an error.

## Environment

- Operating system: Ubuntu 20.04
- Python version: 3.8.10
- OpenCV version: 4.5.4

## Additional information

I tried different image formats (jpg, png, bmp) and sizes, but none of them worked. I also checked the permissions of the input folder and the images, and they are readable by the script.

**Comment by GaganHonor** [comment]
Hello Thanks a lot for your review , The issue is you have to add your own images as directory inside the training images directory 
of the repo , hope this help and follow all read me instructions 😊

**Comment by BeingTraveler** [comment]
Thanks a lot bro ❤️ thanks for being quick
